
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# NOTE: DO *NOT* EDIT THIS FILE.  IT IS GENERATED.
# PLEASE UPDATE Dockerfile.txt INSTEAD OF THIS FILE
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
FROM selenium/standalone-chrome

RUN sudo apt-get update && sudo apt-get install -y iputils-ping

LABEL maintainer="Edmund Luong <edmundvmluong@gmail.com>"

EXPOSE 4444
